apiVersion: v1
kind: Service
metadata:
  name: inner-gateway-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9800
    targetPort: 9800
    name: inner-gateway-server-port
    nodePort: 9800
  selector:
    tier: inner-gateway-server
