apiVersion: v1
kind: Service
metadata:
  name: sc-admin-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 6500
    targetPort: 6500
    name: sc-admin-server-port
    nodePort: 6500
  selector:
    tier: sc-admin-server
