apiVersion: v1
kind: Service
metadata:
  name: uaa-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    name: uaa-server-port
    nodePort: 8000
  selector:
    tier: uaa-server
