apiVersion: v1
kind: Service
metadata:
  name: user-center-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 7000
    targetPort: 7000
    name: user-center-server-port
    nodePort: 7000
  selector:
    tier: user-center-server
