apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9900
    targetPort: 9900
    name: zuul-gateway-server-port
    nodePort: 9900
  selector:
    tier: zuul-gateway-server
