server:
  port: 11001

spring:
  profiles:
    active: sharding-databases2
  application:
    name: sharding-jdbc-demo

houyi:
  datasource:
    ip: saas-mysql
    username: root
    password: password

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.sharding.demo.model
  global-config:
    db-config:
      id-type: ID_WORKER