sharding:
  jdbc:
    datasource:
      names: ds-anbang,ds-fujia
      ds-anbang:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${houyi.datasource.ip}:3306/demo_ds_anbang?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: ${houyi.datasource.username}
        password: ${houyi.datasource.password}
      ds-fujia:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${houyi.datasource.ip}:3306/demo_ds_fujia?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: ${houyi.datasource.username}
        password: ${houyi.datasource.password}
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: company_id
            algorithm-expression: ds-$->{company_id}
        tables:
          user:
            actual-data-nodes: ds-$->{['anbang','fujia']}.user
            key-generator-column-name: id
      props:
        sql:
          show: true